# -*- mode: ruby -*-
# # vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define "fmp-db1-server" do |db1|
        db1.vm.box = "centos/7"
        db1.vm.hostname = "postgres1"

        db1.vm.network :forwarded_port, guest: 22, host: 12822, id: 'ssh'
        db1.vm.network :private_network, ip: '192.168.32.51'

        db1.vm.provision "shell", inline: <<-SHELL
        sudo bash /vagrant/shell/db_master.sh

        SHELL
        db1.vm.provider "virtualbox" do |v|
            v.name = "fmp-db1-server"
        end
    end
    config.vm.define "fmp-front-server" do |app|
      app.vm.box = "centos/7"
      app.vm.hostname = "app"

      app.vm.network :forwarded_port, guest: 5000, host: 5000, id: 'app'
      app.vm.network :forwarded_port, guest: 3000, host: 3000, id: 'app'
      app.vm.network :private_network, ip: '192.167.32.53'

      app.vm.provision "shell", inline: <<-SHELL
      cd /vagrant/frontend/
      yum install -y gcc-c++ make
      curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -
      sudo yum install -y nodejs
      npm i
      # npm build
      # npm i -g serve && serve -s build &
      npm start & 
      SHELL
      app.vm.provider "virtualbox" do |v|
        v.name = "fmp-app-server"
      end
    end
    config.vm.define "fmp-api-server" do |api|
        api.vm.box = "centos/7"
        api.vm.hostname = "api"

        api.vm.network :forwarded_port, guest: 22, host: 12824, id: 'ssh'
        api.vm.network :private_network, ip: '192.168.32.52'

        api.vm.provision "shell", inline: <<-SHELL
            sudo yum install -y maven
            cd /vagrant/api/
            sudo mvn clean spring-boot:run
        SHELL
        #api.vm.provision "file", source: "~/Documents/alexleokyky/vagrant/FMP/api/", destination: "$HOME/remote/api/"
        api.vm.provider "virtualbox" do |v|
            v.name = "fmp-api-server"
        end
    end
    config.vm.define "fmp-db2-server" do |db2|
        db2.vm.box = "centos/7"
        db2.vm.hostname = "postgres2"

        db2.vm.network :forwarded_port, guest: 22, host: 12823, id: 'ssh'
        db2.vm.network :private_network, ip: '192.168.32.50'

        db2.vm.provision "shell", inline: <<-SHELL
        sudo bash /vagrant/shell/db_slave.sh

        SHELL
        db2.vm.provider "virtualbox" do |v|
            v.name = "fmp-db2-server"
        end
    end
end
