# -*- mode: ruby -*-
# # vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "postgres1"

  config.vm.network :forwarded_port, guest: 22, host: 12822, id: 'ssh'
  config.vm.network :private_network, ip: '192.168.32.51'

  config.vm.provision "shell", inline: <<-SHELL
sudo bash /vagrant/shell/db_master.sh

SHELL
  config.vm.provider "virtualbox" do |v|
    v.name = "centos-api"
  end
end
